print("Hello World!")
s= "my name is ayush nautiyal" 
print(len(s))
print(type(s))
print(s.find("ayush"))
print(s.find('a'))
print(s.find("A"))
s3 = "my name is ayush nautiyal and iam a good  boy ."
print(s3.find('ay'))
print(s3.count('a'))
print(s3.upper())
print(s3.lower())
print(s3)
s3= s3.upper()
print(s3)
print(s3.swapcase())
print(s3.title())
s3=s3.lower()
print(s3.capitalize())
s= "ayush nautiyal"
print(s[0])  
print(s[-1])
print(s[0:4])
print(s[0:8:2])
print(s[0:8:1])
print(s[0:200:2])
print(s[0:2:-1])
print(s[6:1:-1])
print(s[15:0:-1])
print(s[15::-1])
print(s[::-1])

